var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                            o   ",
   "                                                      xxxxx               x!xxxx",
   "                                                                                ",
   "                                                    o             xxxx          ",
   "                                                  xxx      xx                   ",
   "                                             xx                                 ",
   "                                                                                ",
   "                  g              xx!xx                   o                      ",
   "                 xxxx        o                          xxx                 xx  ",
   "  xx                        xxx                                              x  ",
   "  x                                                 p                        x  ",
   "  x          o                                    xxxx                     o x  ",
   "  x          x                                                               x  ",
   "  x  @     xxx    p                                                          x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx!!!!!xxxxxxx  ",
   "                         xxxxxxxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                        o                                                                                         ",
   "                      xxxxx    p                                                                                  ",
   "                             xxxxx       g                                         x       o x                    ",
   "                                        xxxx   xx    x                             x      xxxx                    ",
   "                                               x     x      o                      x         x                    ",
   "                                               x     x       p                     xxx       x                    ",
   "                                               x     x     xxxxxx            xxxxxxx         x                    ",
   "                                               x    xx               x   x o x            xxxx                    ",
   "     @                                         x     x               x   xxxxx               x                    ",
   "    xxx                               p  o  p  x     x               x           xxx         x                    ",
   "xxxxx xxx|xxxx         xxxxxxx   o  xxxxxxxxxxxx     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!x       xxxxxxxxxxxx    x!!|!!!!!!!!!|!!x     =     x xx        x                    ",
   "!!!!x x!!!!!!x         x!!!!!x                       x!!!!!!!xxxxxxxxxxxxxxxxxxxxx xx    o  xx                    ",
   "!!!!x x!!!!!!x       xxx!!!!!x   o                  xx!!!!!!xx                      xxp    xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x             =       xx!!!!!!xx                        xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!x        xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "!!!!x x!!!!!!x p   o p x!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
   "xxxxx x!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                         o                                                                    ",
   "                                     xxxxxxx        p                                                         ",
   "                                                   xxxxx                                                      ",
   "                                                            oo                                                ",
   "                                                     xxxxxxxxxxxx                                             ",
   "                                            o                                                                 ",
   "                                          xxxxxx                                                              ",
   "                                          x                                                                   ",
   "                                  xxxx    x          xxxxxx                                                   ",
   "                                          xx                                                                  ",
   "                                       xxxxxxxx       x                                                       ",
   "                                                      x           xxxxx                                       ",
   "                                                   xxxx     o      xxx                                        ",
   "                                    xxxxxxxxxxx       x                     xxxxx                             ",
   "                              o   o   x x x           x    xxx               xxx        p                     ",
   "                                      x x x           x              x                 xxxxx                  ",
   "                           xxxxx|xxxxxxxxxxx     o o  x!!!!!!!!!!!!!!x                  xxx                   ",
   "                           xxxxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!x                            o           ",
   "                                           x    xxxxxxxxvxxxxxxxxxvxxxxxxx                       xxxxx        ",
   "   o        p              g               xx                                                                 ",
   "  xxx     xxxxxxxx       xxxxxx                                                                               ",
   "  x x                         x              o                             o                             xxx  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                    xxxxx    x  ",
   "  x                           xxx        px                oo            x x x                             x  ",
   "  x                                    xxxx       xxxxxxxxxxxxxxxx     xxx xxx            xxxxx            x  ",
   "  x                                o o    x                              x          o                      x  ",
   "  x                           xx          x                         xxxxxxx       xxxxx                    x  ",
   "  x                           x    xxx    x                             x x                                x  ",
   "  x                           xxx|xxxxxxxxx                            xxxxxxx                             x  ",
   "  x      @                  xxx           x!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx                              x  ",
   "  xxxxxxxxxxxx!!!!!!!xxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "                                                                                                              ",
   "                                                                                                              "],
   ["                                                                                ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
    "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
    "  xxxxxxxxxxxxxxxvxxxxxxxxxxxxxxvxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxx  ",
    "  x                                                                  o       x  ",
    "  x     o                                          o         p     xxxx      x  ",
    "  x   xxxx                                        xxx      xxxxxx            x  ",
    "  x             x         p               xxxxxxx                            x  ",
    "  x                    xxxxxxx                          o                    x  ",
    "  x    xxxxxxx                    xxxx                xxxxxx                 x  ",
    "  x                                                                p         x  ",
    "  x       o       xxxxx                                        xxxxxx        x  ",
    "  x    xxxxxxx              o                       p     x                  x  ",
    "  x                       xxxxxx                  xxxx                       x  ",
    "  x                                       xxx                                x  ",
    "  x  @                                                                    g  x  ",
    "  xxxxx!!!!!xxxx!!!!xxxxxx!!!!!!!xxx!!!xxx!!!xxxxxxxxx!!!!!xxxxxxx!!!!!xxxxxxx  ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "      x      x  xxxxxxx  x    x     x   x   x     x    xx     x      x          ",
    "       x    x   x     x  x    x     x   x   x     x    x x    x      x          ",
    "        x  x    x     x  x    x     x   x   x     x    x  x   x      x          ",
    "          x     x     x  x    x     x   x   x     x    x   x  x      x          ",
    "          x     x     x  x    x     x   x   x     x    x    x x     x x         ",
    "          x     xxxxxxx  xxxxxx     xxxxxxxxx     x    x     xx     x x         ",
    "                                                                                ",
    "  xx                                                                        xx  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x  @                                                                       x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
